# -*- coding: utf-8 -*-
from . import dl_wood_log
from . import dl_wood_log_config
from . import dl_wood_log_mixin
from . import dl_wood_dossier
from . import dl_wood_species
from . import dl_dossier_ledger
from . import dl_co_declaration
from . import sale_order
from . import dl_contract_template
from . import res_partner
from . import dl_woodpro_config
from . import product_template
from . import stock_move_line
from . import dl_wood_exploitation_location
from . import dl_wood_production
from . import res_company
from . import res_config_settings
from . import dl_wood_transport
from . import dl_vietnam_bank
from . import dl_wood_dossier_inventory
from . import res_country_state
from . import res_country_ward
