# -*- coding: utf-8 -*-
{
    'name': 'DL Wood Payroll',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Quản lý đơn giá và bảng giá nhân công ngành gỗ',
    'description': """
        Module quản lý đơn giá sản phẩm và tính lương theo sản phẩm.
        Các tính năng chính:
        - Thêm tổ gốc và phân loại lao động thời vụ cho nhân viên.
        - Quản lý bảng giá đơn giá công đoạn.
        - Tính năng sao chép bảng giá từ tháng trước.
    """,
    'author': 'Antigravity',
    'depends': ['hr', 'mrp', 'mail', 'product', 'sale', 'stock', 'account', 'hr_attendance'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/dl_attendance_type_data.xml',
        'views/dl_workshop_views.xml',
        'views/cao_bang/hr_department_views.xml',
        'views/cao_bang/dl_employee_transfer_views.xml',
        'views/cao_bang/hr_employee_views.xml',
        'views/khoan_viec/dl_film_pricelist_views.xml',
        'views/product_template_views.xml',
        'views/mrp_workcenter_views.xml',
        'views/cao_bang/dl_production_group_views.xml',
        'views/khoan_viec/dl_piece_rate_pricelist_views.xml',
        'views/cao_bang/dl_attendance_type_views.xml',
        'views/khoan_viec/dl_production_log_views.xml',
        'views/cao_bang/dl_daily_attendance_views.xml',
        'views/cao_bang/dl_daily_pooling_result_views.xml',
        'wizard/dl_pooling_wizard_views.xml',
        'wizard/dl_missing_attendance_wizard_views.xml',
        'wizard/dl_pricelist_excel_wizard_views.xml',
        'wizard/dl_film_wizard_views.xml',
        'wizard/dl_comprehensive_excel_wizard_views.xml',
        'wizard/dl_film_matrix_viewer_views.xml',
        'wizard/dl_clean_data_wizard_views.xml',
        'wizard/dl_global_payroll_wizard_views.xml',
        'views/cao_bang/dl_fine_views.xml',
        'data/dl_fine_data.xml',
        'data/dl_film_brand_data.xml',
        'data/dl_combined_log_data.xml',
        'views/cao_bang/dl_combined_log_views.xml',
        'views/integration_views.xml',
        'views/dl_missing_attendance_client_views.xml',
        'data/dl_stevedore_log_data.xml',
        'data/pickup/pickup_sequence.xml',
        'views/stevedore/dl_stevedore_views.xml',
        'views/pickup/dl_wood_pickup_views.xml',
        'views/khoan_viec/dl_veneer_drying_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dl_wood_payroll/static/src/scss/wood_ui.scss',
            'dl_wood_payroll/static/src/scss/missing_attendance_view.scss',
            'dl_wood_payroll/static/src/js/missing_attendance_view.js',
            'dl_wood_payroll/static/src/xml/missing_attendance_view.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
