from . import hr_employee
from . import product_template
from . import dl_combined_log
from . import dl_piece_rate_pricelist
from . import dl_production_log
from . import dl_attendance_type
from . import dl_daily_attendance
from . import dl_production_group
from . import dl_workshop
from . import hr_department
from . import mrp_workcenter
from . import dl_daily_pooling_result
from . import dl_employee_transfer
from . import product_attribute
from . import wood_integration
from . import dl_fine
from . import dl_film_brand
from . import dl_film_pricelist
from . import dl_stevedore_log
from . import dl_payroll_matrix_report
from . import dl_veneer_drying
