# -*- coding: utf-8 -*-
{
    'name': 'Đức Lâm - Truy Xuất Nguồn Gốc Gỗ',
    'version': '19.0.2.0.0',
    'summary': 'Quản lý truy xuất nguồn gốc gỗ, hồ sơ kiểm lâm và trừ lùi song song (Nội bộ và Khai báo CO)',
    'category': 'Inventory/Warehouse',
    'author': 'Đức Lâm ERP',
    'depends': ['base', 'sale', 'stock', 'product', 'mrp', 'mail'],
    'data': [
        'security/dl_wood_security.xml',
        'security/dl_wood_multi_company.xml',
        'security/ir.model.access.csv',
        'data/dl_wood_species_data.xml',
        'data/ir_sequence_data.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/dl_wood_log_views.xml',
        'views/ui_cleanup_views.xml',
        'views/dl_traceability_views.xml',
        'views/dl_wood_production_views.xml',
        'views/mrp_production_views.xml',
        'views/stock_picking_views.xml',
        'views/res_config_settings_views.xml',
        'wizard/dl_customer_import_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
