# -*- coding: utf-8 -*-
{
    'name': 'Đức Lâm - Hồ Sơ Gỗ',
    'version': '19.0.2.0.0',
    'summary': 'Quản lý hồ sơ gỗ, hồ sơ kiểm lâm và trừ lùi song song (Nội bộ và Khai báo CO)',
    'category': 'Inventory/Warehouse',
    'author': 'Đức Lâm ERP',
    'depends': ['base', 'sale', 'stock', 'product', 'mrp', 'mail', 'dl_wood_product_base', 'dl_public_holiday'],
    'data': [
        'security/dl_wood_security.xml',
        'security/dl_wood_multi_company.xml',
        'security/ir.model.access.csv',
        'data/dl_wood_species_data.xml',
        'data/dl_report_version_data.xml',
        'data/ir_sequence_data.xml',
        'data/dl_wood_log_data.xml',
        'views/dl_traceability_views.xml',
        'views/dl_wood_production_views.xml',
        'views/res_partner_views.xml',
        'views/dl_wood_peeling_type_views.xml',
        'views/product_template_views.xml',
        'views/dl_wood_log_views.xml',
        'views/ui_cleanup_views.xml',
        'views/dl_wood_transport_views.xml',
        'views/dl_wood_dossier_inventory_views.xml',
        'views/mrp_production_views.xml',
        'views/stock_picking_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_country_ward_views.xml',
        'views/dl_vietnam_bank_views.xml',
        'wizard/dl_wood_peeling_import_wizard_views.xml',
        'wizard/dl_wood_peeling_production_wizard_views.xml',
        'views/dl_wood_peeling_views.xml',
        'wizard/dl_customer_import_wizard_views.xml',
        'wizard/dl_wood_init_data_wizard_views.xml',
        'wizard/dl_wood_dossier_consumption_wizard_views.xml',
        'wizard/dl_wood_peeling_invoice_export_wizard_views.xml',
        'views/dl_wood_peeling_report_views.xml',
        'views/menus.xml',
        'views/dl_misa_extension_release_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dl_wood_traceability/static/src/libs/jsQR.js',
            'dl_wood_traceability/static/src/views/fields/qr_image/qr_image_field.js',
            'dl_wood_traceability/static/src/views/fields/qr_image/qr_image_field.xml',
            'dl_wood_traceability/static/src/css/wood_traceability.css',
            'dl_wood_traceability/static/src/js/dossier_image_preview.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
